server:
  port: 1112

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 30000

spring:
  application:
    name: eureka-server