server:
  port: 8083
  
spring:
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
zuul:
#配置路由转发规则，将符合/api-test/**规则的访问转发给microservice
  routes:
    api-test:
      path: /api-test/**
      serviceId: microservice
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000